[buildpack]
name = "Ruby"
ruby_version = "2.6.9"

[publish.Ignore]
files = [
  "changelogs/",
  "spec/",
  "Gemfile",
  "Gemfile.lock",
  "Rakefile",
  "app.json",
  "hatchet.json",
  "hatchet.lock",
]

[[publish.Vendor]]
url = "https://heroku-buildpack-rg.s3.us-east-1.amazonaws.com/ruby-2.6.9.tgz"
dir = "vendor/ruby/heroku-24"

[[stacks]]
id = "heroku-24"