api = "0.2"

[buildpack]
name = "Ruby"
ruby_version = "2.6.9"

[publish]

[publish.Ignore]
files = ["spec/"]

[[publish.Vendor]]
url = "https://heroku-buildpack-rg.s3.us-east-1.amazonaws.com/ruby-2.6.9.tgz"

[[stacks]]
id = "heroku-24"


[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-ruby-buildpack"