[buildpack]
name = "Ruby"
ruby_version = "2.6.9"
app = "depanneur"

[publish.Ignore]
files = [
  "changelogs/",
  "spec/",
  "Gemfile",
  "Gemfile.lock",
  "Rakefile",
  "app.json",
  "hatchet.json",
  "hatchet.lock",
]
